spring:
    data:
        rest:
            base-path: /api
    datasource:
        url: jdbc:h2:file:./src/main/resources/CardSwaprDB
        username: sa
        password: ''
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-ui
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

